#!/bin/sh

# Script for backing up files. Uses script from https://github.com/wolfv6/rclone_jobber. 

source="~/Documents"
dest="/run/media/$USER/usb/Backup/$USER-at-archlinux/Documents"
move_old_files_to="dated_files"

rclone_jobber "$source" "$dest" "$move_old_files_to"
