#! /bin/bash

mkdir -p JPG

for xcf_file in *.xcf; do
    jpg_file="JPG/${xcf_file%.*}.jpg"
    gimp -i -d -b "(save_as_jpg \"$xcf_file\" \"$jpg_file\")" -b "(gimp-quit 0)" 
done
file_name=$(basename "${PWD%/*}")
file_name="${file_name//[ ,-]/_}"
file_name="${file_name//___/_}"
file_name=$file_name"___Lesson_Summary"
convert JPG/*.jpg "../$file_name".pdf
rm -R JPG
