#!/bin/bash

filename="main"
foldername="output"
mkdir -p $foldername
mkdir -p $foldername/tikz
find $foldername -maxdepth 1 -name "main*" -exec mv -t . {} +
texfot pdflatex -shell-escape $filename

while getopts :bai opt; do
  case $opt in
    b) bibtex $filename
      texfot pdflatex -shell-escape $filename
      texfot pdflatex -shell-escape $filename
      ;;
    a) makeglossaries $filename
      texfot pdflatex -shell-escape $filename
      texfot pdflatex -shell-escape $filename
      ;;
    i) makeindex $filename
      texfot pdflatex -shell-escape $filename
      ;;
    ?) echo "I don't know what $OPTARG is!"
  esac
done

find . -maxdepth 1 -name "main*" ! -name main.tex -exec mv -t $foldername {} +
cd $foldername
new_name=$(basename "${PWD%/*}.pdf")
mv main.pdf "$new_name"
