#!/bin/bash

export DISPLAY=":0"

# Get connected monitors
connected_monitors=$(xrandr --query | grep " connected" | awk '{ print $1 }')

# Loop through connected monitors and set brightness and gamma
for monitor in $connected_monitors; do
    echo "Adjusting brightness and gamma for $monitor."
    xrandr --output "$monitor" --brightness 0.5 --gamma 1.0:0.7:0.5
done

echo "Brightness and gamma adjustments complete."

