#!/bin/sh

temperature=$(sensors | awk '/Composite/ {print $2}' | sed 's/+//g');
if [ -z "$temperature" ]
then
  temperature=$(sensors | awk '/CPU/ {print $2}' | sed 's/+//g');
fi
temperature=${temperature%.*}

if [ "$temperature" -lt 75 ]
then
  icon=""
else
  icon=""
fi

echo "$icon $temperature°C"
