#!/bin/sh

VOLUME_MUTE=""
VOLUME_ZERO=""
VOLUME_LOW=""
VOLUME_HIGH=""
SOUND_LEVEL=$(amixer -M get Master | awk -F"[][]" '/%/ { print $2 }' | awk -F"%" 'BEGIN{tot=0; i=0} {i++; tot+=$1} END{printf("%s\n", tot/i) }')
MUTED=$(amixer get Master | awk ' /%/{print ($NF=="[off]" ? 1 : 0); exit;}')

ICON=$VOLUME_MUTE
if [ "$MUTED" = "1" ]
then
    ICON="$VOLUME_MUTE"
else
    if [ "$SOUND_LEVEL" -eq 0 ]
    then
        ICON="$VOLUME_ZERO"
    elif [ "$SOUND_LEVEL" -lt 50 ]
    then
        ICON="$VOLUME_LOW"
    else
        ICON="$VOLUME_HIGH"
    fi
fi

echo "$ICON" "$SOUND_LEVEL"
